name: game_of_queens
description: A flutter chess puzzle about placing Queens

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  provider: ^6.0.3
  confetti: ^0.7.0
  alchemist: ^0.3.3
  golden_toolkit: ^0.13.0
  dart_code_metrics: ^4.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: RainyHearts
      fonts:
        - asset: assets/rainyhearts.ttf